version: 'latest'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - mongo-express
    command: python3 conf.py

  mongodb:
    container_name: mongo-main
    image: mongo:6-jammy
    env_file:
      .env
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 28081:8081
    env_file:
      .env
    depends_on:
      - mongodb

