[tool.poetry]
name = "mongo-repo"
version = "0.1.0"
description = "Simple lib that dynamically creates repositories for mongo db"
authors = ["artorias <kerelkobarabash@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
motor = "^3.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
