version: 'latest'

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app
    depends_on:
      - mongodb
      - mongo-express
    command: python3 -m http.server 8000

  mongodb:
    container_name: mongo-main
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - ../data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 28081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
